# Generated by Django 5.2.9 on 2025-12-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('difficulty', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('difficulty', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
